#!/usr/bin/env python3
"""Regression tests for the four-relay encoder GPIO pullup boundary."""

from __future__ import annotations

import sys
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SCRIPT_DIR = ROOT / "scripts"
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from scaffold_audit_firmware import audit_encoder_menu_boundary  # noqa: E402


MAIN_C = ROOT / "firmware/projects/four-relay-xbee-wifi/main/main.c"
GENERATED_MENU_H = ROOT / "firmware/projects/four-relay-xbee-wifi/main/bbs_lcd_menu_generated.h"


def firmware_source_text() -> str:
    return MAIN_C.read_text(encoding="utf-8") + "\n" + GENERATED_MENU_H.read_text(encoding="utf-8")


class FirmwareEncoderPullupBoundaryTests(unittest.TestCase):
    def test_pf0530f_devkitc_gpio_pull_policy_is_source_visible(self) -> None:
        source = firmware_source_text()

        self.assertIn("FR_ENCODER_CLK_GPIO GPIO_NUM_13", source)
        self.assertIn("FR_ENCODER_DT_GPIO GPIO_NUM_14", source)
        self.assertIn("FR_ENCODER_SW_GPIO GPIO_NUM_32", source)
        self.assertIn("{FR_ENCODER_CLK_GPIO, \"CLK\", true}", source)
        self.assertIn("{FR_ENCODER_DT_GPIO, \"DT\", true}", source)
        self.assertIn("{FR_ENCODER_SW_GPIO, \"SW\", true}", source)
        self.assertIn("fr_gpio_sweep_pins[index].enable_pullup", source)
        self.assertIn("gpio_config(&config)", source)
        self.assertIn(".mode = GPIO_MODE_INPUT", source)
        self.assertIn(".pull_up_en = enable_pullup ? GPIO_PULLUP_ENABLE : GPIO_PULLUP_DISABLE", source)
        self.assertIn(".pull_down_en = GPIO_PULLDOWN_DISABLE", source)
        self.assertNotIn("gpio_pullup_en(pins[index])", source)
        self.assertNotIn("FR_ENCODER_CLK_GPIO GPIO_NUM_34", source)
        self.assertNotIn("FR_ENCODER_DT_GPIO GPIO_NUM_35", source)
        self.assertNotIn("FR_ENCODER_SW_GPIO GPIO_NUM_13", source)
        self.assertNotIn("{FR_GPIO_SWEEP_GPIO32, \"32\", false}", source)

    def test_pf0530p_bbs_menu_uses_lcd_init_diag_path(self) -> None:
        source = firmware_source_text()

        self.assertIn("FR_DIAG_FIRMWARE_ID \"PF0530W\"", source)
        self.assertIn("FR_DIAG_FIRMWARE_ID_VALUE \"PF0530W\"", source)
        self.assertIn("LCD_DIAG_READY gpio=21/22 speed=%d pullups=external", source)
        self.assertIn("LCD_BUS result=ok", source)
        self.assertIn("LCD_PROBE addr=0x%02x result=ack", source)
        self.assertIn("LCD_PROBE_SUMMARY count=%u selected=0x%02x", source)
        self.assertIn("LCD_DEVICE result=ok addr=0x%02x", source)
        self.assertIn("LCD_HD44780 step=%s result=%s err=%s", source)
        self.assertIn("LCD_INIT_OK addr=0x%02x", source)
        self.assertIn("LCD_INIT_FAIL stage=", source)
        self.assertIn("LCD_DIAG_HB status=%s count=%lu addr=0x%02x stage=%s devices=%u", source)
        self.assertIn("fr_lcd_bbs_menu_task", source)
        self.assertIn("xTaskCreate(\n        fr_lcd_bbs_menu_task", source)
        self.assertNotIn("xTaskCreate(\n        fr_lcd_diag_task", source)
        self.assertIn("FR_MENU_PAGE_COUNT FR_BBS_MENU_PAGE_COUNT", source)
        self.assertIn("FR_BBS_MENU_PAGE_COUNT 15u", source)
        self.assertIn("FR_MENU_POLL_MS 2", source)
        self.assertIn("FR_MENU_RENDER_POLL_MS 20", source)
        self.assertIn("FR_MENU_IDLE_REFRESH_MS 60000", source)
        self.assertIn("FR_MENU_AUTO_CYCLE_ENABLED 0U", source)
        self.assertIn("FR_MENU_AUTO_CYCLE_MS 7000", source)
        self.assertIn("FR_MENU_ANIMATION_MS 2000", source)
        self.assertIn("FR_GLYPH_BANK_COUNT FR_BBS_GLYPH_BANK_COUNT", source)
        self.assertIn("FR_BBS_GLYPH_BANK_COUNT 7u", source)
        self.assertIn("FR_GLYPH_SLOTS 8", source)
        self.assertIn("FR_GLYPH_ROWS 8", source)
        self.assertIn("FR_GLYPH_BANK_SWAP_MIN_MS 250", source)
        self.assertIn("FR_ENCODER_AB_STABLE_SAMPLES 1", source)
        self.assertIn("FR_ENCODER_AB_DEBOUNCE_MS 1", source)
        self.assertIn("FR_ENCODER_AB_QUIET_MS 0", source)
        self.assertIn("FR_ENCODER_DETENT_AB 3U", source)
        self.assertIn("FR_ENCODER_TRANSITIONS_PER_STEP 1", source)
        self.assertIn("FR_ENCODER_STEP_LOCKOUT_MS 25", source)
        self.assertIn("FR_ENCODER_SW_GUARD_MS 40", source)
        self.assertIn("FR_ENCODER_PCNT_LOW_LIMIT -32767", source)
        self.assertIn("FR_ENCODER_PCNT_HIGH_LIMIT 32767", source)
        self.assertIn("FR_ENCODER_PCNT_RECENTER_LIMIT 30000", source)
        self.assertIn("FR_ENCODER_PCNT_GLITCH_NS 1000", source)
        self.assertIn("FR_ENCODER_PCNT_COUNTS_PER_STEP 4", source)
        self.assertIn("FR_ENCODER_PCNT_MAX_STEPS_PER_POLL 4", source)
        self.assertIn("FR_ENCODER_PCNT_DIR_SIGN 1", source)
        self.assertIn("FR_MENU_HEARTBEAT_MS 2000", source)
        self.assertIn("FR_ENCODER_RAW_HEARTBEAT_MS 1000", source)
        self.assertIn("FR_ENCODER_RAW_EVENT_LOG_ENABLED 0U", source)
        self.assertIn("FR_ENCODER_INTERRUPT_TELEMETRY 0U", source)
        self.assertIn("FR_ENCODER_DETENT_GATED 1U", source)
        self.assertIn("FR_MENU_INPUT_TASK_PRIORITY (tskIDLE_PRIORITY + 1)", source)
        self.assertIn("FR_MENU_MODE_PAGE_BROWSE", source)
        self.assertIn("FR_MENU_MODE_ROW_BROWSE", source)
        self.assertIn("FR_MENU_MODE_DETAIL", source)
        self.assertIn("FR_MENU_MODE_EDIT_LAB", source)
        self.assertIn("fr_delay_ticks_at_least_one", source)
        self.assertIn("FR_ENCODER_EVENT_QUEUE_DEPTH 0", source)
        self.assertIn("FR_ENCODER_IRQ_DRAIN_LIMIT 0", source)
        self.assertIn("#include \"driver/pulse_cnt.h\"", source)
        self.assertIn("pcnt_new_unit", source)
        self.assertIn("pcnt_unit_set_glitch_filter", source)
        self.assertIn("pcnt_new_channel", source)
        self.assertIn("pcnt_channel_set_edge_action", source)
        self.assertIn("pcnt_channel_set_level_action", source)
        self.assertIn("pcnt_unit_enable", source)
        self.assertIn("pcnt_unit_clear_count", source)
        self.assertIn("pcnt_unit_start", source)
        self.assertIn("pcnt_unit_get_count", source)
        self.assertIn("fr_encoder_pcnt_accumulate_steps", source)
        self.assertIn("fr_menu_process_pcnt", source)
        self.assertIn("fr_menu_resync_pcnt", source)
        self.assertIn("fr_encoder_irq_count", source)
        self.assertIn("fr_encoder_pin_mask", source)
        self.assertIn("gpio_dump_io_configuration(stdout, fr_encoder_pin_mask())", source)
        self.assertIn(".intr_type = FR_ENCODER_INTERRUPT_TELEMETRY != 0U", source)
        self.assertIn(": GPIO_INTR_DISABLE", source)
        self.assertNotIn("#include \"freertos/queue.h\"", source)
        self.assertNotIn("fr_encoder_irq_event_t", source)
        self.assertNotIn("fr_encoder_event_queue", source)
        self.assertNotIn("fr_encoder_isr_handler", source)
        self.assertNotIn("xQueueCreate(", source)
        self.assertNotIn("xQueueSendFromISR(", source)
        self.assertNotIn("xQueueReceive(fr_encoder_event_queue", source)
        self.assertNotIn("gpio_install_isr_service(0)", source)
        self.assertNotIn("gpio_isr_handler_add(", source)
        self.assertIn("FR_GPIO_SWEEP_COUNT 3", source)
        self.assertIn("cw_step_count", source)
        self.assertIn("ccw_step_count", source)
        self.assertIn("pcnt_last_count", source)
        self.assertIn("pcnt_last_delta", source)
        self.assertIn("pcnt_residual", source)
        self.assertIn("pcnt_step_count", source)
        self.assertIn("pcnt_capped_poll_count", source)
        self.assertIn("pcnt_direction_flip_count", source)
        self.assertIn("pcnt_guard_reset_count", source)
        self.assertIn("pcnt_suppressed_delta_count", source)
        self.assertIn("pcnt_recenter_count", source)
        self.assertIn("ab_debounce_hold_count", source)
        self.assertIn("ab_quiet_hold_count", source)
        self.assertIn("accepted_stable_ab_transition_count", source)
        self.assertIn("detent_return_count", source)
        self.assertIn("detent_step_count", source)
        self.assertIn("detent_partial_count", source)
        self.assertIn("step_lockout_count", source)
        self.assertIn("poll_count", source)
        self.assertIn("queue_receive_count", source)
        self.assertIn("raw_ab_burst_count", source)
        self.assertIn("last_raw_ab_gap_ms", source)
        self.assertIn("last_ab_held_ms", source)
        self.assertIn("last_ab_quiet_ms", source)
        self.assertIn("invalid_transition_count", source)
        self.assertIn("suppressed_transition_count", source)
        self.assertIn("signal_change_count", source)
        self.assertIn("switch_guard_until_ms", source)
        self.assertIn("candidate_changed_ms_a", source)
        self.assertIn("candidate_changed_ms_b", source)
        self.assertIn("last_step_ms", source)
        self.assertIn("last_heartbeat_ms", source)
        self.assertIn("last_level_heartbeat_ms", source)
        self.assertIn("fr_menu_sample_ab_pair", source)
        self.assertIn("fr_menu_ab_a", source)
        self.assertIn("fr_menu_ab_b", source)
        self.assertIn("fr_menu_raw_ab", source)
        self.assertIn("fr_menu_process_levels", source)
        self.assertIn("fr_menu_handle_switch_stable", source)
        self.assertIn("fr_menu_sample_inputs", source)
        self.assertIn("fr_menu_input_task", source)
        self.assertIn("selected_item", source)
        self.assertIn("viewport_top_line", source)
        self.assertIn("page_stack", source)
        self.assertIn("FR_MENU_PAGE_STACK_DEPTH 4", source)
        self.assertIn("fr_bbs_generated_pages", source)
        self.assertIn("fr_bbs_sync_menu_view", source)
        self.assertIn("fr_bbs_render_generated_frame", source)
        self.assertIn("fr_lcd_render_cache_t", source)
        self.assertIn("render_cache.valid", source)
        self.assertIn("runtime.lcd_dirty", source)
        self.assertIn("fr_diag_short_display_count", source)
        self.assertIn("fr_diag_short_position_magnitude", source)
        self.assertIn("fr_bbs_page_name", source)
        self.assertIn("BBS FIELD STATUS", source)
        self.assertIn("MSG NEW:01 IN:12", source)
        self.assertIn("PEERS ACTIVE 2/3", source)
        self.assertIn("QUEUE P:2 F:0", source)
        self.assertIn("FILES Q:1 D:3", source)
        self.assertIn("MESH runtime", source)
        self.assertIn("BRIDGE LOCAL CLOSED", source)
        self.assertIn("DIAG ERRORS:0", source)
        self.assertIn("Flash:LOCK Ser:LOCK", source)
        self.assertIn("BARS LINK QUEUE", source)
        self.assertIn("VERT CHART HISTORY", source)
        self.assertIn("BIG DIGITS 12:34", source)
        self.assertIn("GAUGE STATUS", source)
        self.assertIn("fr_bbs_row_is_editable", source)
        self.assertIn("fr_bbs_row_action_label", source)
        self.assertIn("fr_bbs_format_context_line", source)
        self.assertIn("actions=page,detail,edit,back", source)
        self.assertIn("fr_menu_level_char", source)
        self.assertIn("BBS_LCD_READY gpio=13/14/32 pullups=on lcd=21/22 addr=0x%02x", source)
        self.assertIn("BBS_INPUT_READY task=split poll_ms=%u render=dirty idle_ms=%u ", source)
        self.assertIn("irq=pcnt queue=%u", source)
        self.assertIn("modes=scroll,detail,edit", source)
        self.assertIn("step=%u stable=%u sw_debounce_ms=%u sw_guard_ms=%u long_ms=%u drain=%u", source)
        self.assertIn("cal=pcnt-v1", source)
        self.assertIn("decoder=pcnt sw=poll pcnt=1 counts_per_step=%u", source)
        self.assertIn("max_steps=%u glitch_ns=%u dir=%d recenter=%d", source)
        self.assertIn("ab_ms=%u quiet_ms=%u step_lockout_ms=%u", source)
        self.assertIn("detent=%u detent_gate=%u raw_hb_ms=%u gpio_cfg=1 poll_raw=1 ", source)
        self.assertIn("raw_log=%u poll_decoder=0 source=%s", source)
        self.assertIn("ENC_BASE levels=C%uD%uS%u raw_ab=%u pcnt_count=%ld t=%lu", source)
        self.assertIn("ENC_GPIO_CONFIG pin=%d label=%s mode=input pullup=%s", source)
        self.assertIn("ENC_PCNT_READY result=ok", source)
        self.assertIn("ENC_LEVEL_HB levels=C%uD%uS%u raw_ab=%u stable=C%uD%u", source)
        self.assertIn("ENC_PCNT_HB count=%ld delta=%ld residual=%ld steps=%lu", source)
        self.assertIn("FR_BBS_MENU_XML_SCHEMA", source)
        self.assertIn("FR_BBS_MENU_RENDER_SCHEMA", source)
        self.assertIn("FR_BBS_MENU_MARQUEE_HOLD_MS 750u", source)
        self.assertIn("FR_BBS_MENU_MARQUEE_STEP_MS 250u", source)
        self.assertIn(".name = \"core_status\"", source)
        self.assertIn(".name = \"horizontal_bar\"", source)
        self.assertIn(".name = \"vertical_chart\"", source)
        self.assertIn(".name = \"big_digits\"", source)
        self.assertIn(".name = \"gauge\"", source)
        self.assertIn(".name = \"table\"", source)
        self.assertIn(".name = \"art_panel\"", source)
        self.assertIn("FR_BBS_ART_GLYPH_BANK_INDEX 6U", source)
        self.assertIn("fr_bbs_art_panel_slots", source)
        self.assertIn("LCD art badge panel", source)
        self.assertIn("ART", source)
        self.assertIn("NODE |RSSI|Q", source)
        self.assertIn("ROUTES", source)
        self.assertIn("fr_lcd_load_glyph_bank", source)
        self.assertIn("BBS_GLYPH_BANK name=%s index=%u slots=%u rows=%u", source)
        self.assertIn("BBS_CURSOR row=%u col=%u ddram=0x%02x focus=%s mode=%s", source)
        self.assertIn("BBS_LCD_RENDER page=%s index=%u row0=\\\"%s\\\" row1=\\\"%s\\\"", source)
        self.assertIn("rows=%u seq=%lu dur_ms=%lu reason=%s", source)
        self.assertIn("dirty_rows=0x%02x dirty_cells=%u", source)
        self.assertIn("ENC_RAW kind=%s levels=C%uD%uS%u raw_ab=%lu raw_sw=%lu ", source)
        self.assertIn("gap_ms=%lu burst=%lu t=%lu", source)
        self.assertIn("ENC_EV pin=%d label=%s level=%u count=%lu t=%lu", source)
        self.assertIn("BBS_MENU_STEP dir=%c page=%s index=%u pos=%ld cw=%lu ccw=%lu t=%lu", source)
        self.assertIn("BBS_MENU_SELECT buttons=%lu page=%s index=%u kind=short held_ms=%lu t=%lu", source)
        self.assertIn("BBS_MENU_SELECT buttons=%lu page=%s index=%u kind=long held_ms=%lu t=%lu", source)
        self.assertIn("AB_SUPPRESS raw=%u levels=C%uD%uS%u suppressed=%lu t=%lu", source)
        self.assertIn("AB_INVALID prev=%u curr=%u invalid=%lu t=%lu", source)
        self.assertIn("ENC_FILTER reason=%s prev=%u curr=%u levels=C%uD%uS%u", source)
        self.assertIn("\"ab_debounce\"", source)
        self.assertIn("\"ab_quiet\"", source)
        self.assertIn("\"step_lockout\"", source)
        self.assertIn("\"detent_partial\"", source)
        self.assertIn("\"invalid\"", source)
        self.assertIn("\"sw_guard\"", source)
        self.assertIn("BBS_MENU_HB page=%s index=%u pos=%ld levels=C%uD%uS%u steps=%lu/%lu", source)
        self.assertIn("ab_hold=%lu ab_quiet=%lu stable_ab=%lu detent=%lu detent_step=%lu partial=%lu", source)
        self.assertIn("step_lockout=%lu invalid=%lu suppressed=%lu", source)
        self.assertIn("raw_burst=%lu gap_ms=%lu", source)
        self.assertIn("BBS_MENU_AUTO_CYCLE page=%s index=%u interval_ms=%u t=%lu", source)
        self.assertIn("irq_drop=%lu", source)
        self.assertIn("queue_drop=%lu", source)
        self.assertIn("raw_levels=C%uD%uS%u raw_ab=%u candidate=C%uD%u", source)
        self.assertIn("isr=C%luD%luS%lu queue_rx=%lu poll=%lu", source)
        self.assertNotIn("FR_MENU_REFRESH_MS 250", source)
        self.assertNotIn("FR_DIAG_SERIAL_PINTRACE 1", source)
        self.assertNotIn("SERIAL_PINTRACE READY", source)
        self.assertNotIn("fr_serial_pintrace_start_task", source)
        self.assertNotIn("fr_serial_pintrace_run();", source)
        self.assertNotIn("    menu->page = 0;\n    if (menu->ack", source)

    def test_pf0530f_closes_xbee_bridge_and_keeps_inputs_only(self) -> None:
        source = firmware_source_text()

        self.assertIn("FR_DIAG_XBEE_BRIDGE_CLOSED 1", source)
        self.assertIn("#if !FR_DIAG_XBEE_BRIDGE_CLOSED", source)
        self.assertNotIn("FR_GPIO_SWEEP_GPIO16", source)
        self.assertNotIn("FR_GPIO_SWEEP_GPIO17", source)
        self.assertNotIn("FR_GPIO_SWEEP_GPIO21", source)
        self.assertNotIn("FR_GPIO_SWEEP_GPIO22", source)
        self.assertNotIn("FR_GPIO_SWEEP_GPIO25", source)
        self.assertNotIn("FR_GPIO_SWEEP_GPIO26", source)
        self.assertNotIn("FR_GPIO_SWEEP_GPIO27", source)
        self.assertNotIn("FR_GPIO_SWEEP_GPIO33", source)
        self.assertNotIn("gpio_set_level", source)

    def test_firmware_audit_accepts_current_encoder_pullup_boundary(self) -> None:
        self.assertEqual([], audit_encoder_menu_boundary(ROOT))


if __name__ == "__main__":
    unittest.main()
