#!/usr/bin/env python3
"""Shared constants for ESP32 scaffold audits."""

from __future__ import annotations

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]

REQUIRED_PATHS = [
    "AGENTS.md",
    "README.md",
    ".agents/GOVERNANCE.md",
    ".agents/OWNERSHIP.md",
    ".agents/ROLES.md",
    ".agents/TASK_TEMPLATE.md",
    ".agents/TASK_LOG/0001-workspace-scaffold.md",
    ".agents/TASK_LOG/0002-four-relay-xbee-wifi-design-package.md",
    ".agents/TASK_LOG/0003-esp32project-photo-analysis.md",
    ".agents/TASK_LOG/0004-diy-bench-hardware-blueprint.md",
    ".agents/TASK_LOG/0005-admin-hmi-microsd-assets-logs.md",
    ".agents/TASK_LOG/0006-github-pages-public-diy-site.md",
    ".agents/TASK_LOG/0008-github-pages-workbench-build-guide.md",
    ".agents/TASK_LOG/0011-github-pages-blueprints-schematics.md",
    ".agents/TASK_LOG/0012-xbee-read-only-bench-proof.md",
    ".agents/TASK_LOG/0013-hardware-circuit-improvement-research.md",
    ".agents/TASK_LOG/0014-rd-loop-disabled-skeleton.md",
    ".agents/TASK_LOG/0015-public-wow-factor-workbench.md",
    ".agents/TASK_LOG/0016-codebase-research-integration-review.md",
    ".agents/TASK_LOG/0017-scaffold-qa-contract-hardening.md",
    ".agents/TASK_LOG/0018-public-quality-evidence-page.md",
    ".agents/TASK_LOG/0019-expert-agent-panels-skill.md",
    ".agents/TASK_LOG/0020-github-pages-expert-panels.md",
    ".agents/DECISIONS/ADR-0001-framework-choice.md",
    ".agents/DECISIONS/ADR-0002-four-relay-xbee-wifi-framework.md",
    ".agents/handoffs/0002-design-to-hardware-firmware-qa.md",
    ".agents/handoffs/0003-photo-analysis-to-hardware-qa.md",
    ".agents/handoffs/0004-blueprint-to-hardware-qa.md",
    ".agents/handoffs/0005-admin-hmi-to-firmware-hardware-qa.md",
    ".agents/handoffs/0006-github-pages-public-diy-site.md",
    ".agents/handoffs/0008-github-pages-blueprints-to-release-qa.md",
    ".agents/handoffs/0009-xbee-read-only-proof-to-hardware-comms-qa.md",
    ".agents/handoffs/0010-hardware-circuit-research-to-hardware-qa.md",
    ".agents/handoffs/0011-rd-loop-disabled-skeleton-to-role-lanes.md",
    ".agents/handoffs/0012-codebase-research-integration-to-role-lanes.md",
    ".agents/handoffs/0013-scaffold-qa-contracts-to-role-lanes.md",
    "docs/index.md",
    "docs/agent-coordination.md",
    "docs/handoff-and-review.md",
    "docs/risk-and-safety.md",
    "docs/github-pages-public-site.md",
    "docs/architecture/system-overview.md",
    "docs/architecture/modular-boundaries.md",
    "docs/architecture/board-onboarding-flow.md",
    "docs/architecture/communication-interfaces.md",
    "docs/architecture/board-contract.md",
    "docs/architecture/protocol-contract.md",
    "docs/projects/four-relay-xbee-wifi/README.md",
    "docs/projects/four-relay-xbee-wifi/build-guide.md",
    "docs/projects/four-relay-xbee-wifi/architecture.md",
    "docs/projects/four-relay-xbee-wifi/prototype-blueprint.md",
    "docs/projects/four-relay-xbee-wifi/bench-bring-up-runbook.md",
    "docs/projects/four-relay-xbee-wifi/xbee-read-only-bench-proof.md",
    "docs/projects/four-relay-xbee-wifi/hardware-circuit-improvement-research.md",
    "docs/projects/four-relay-xbee-wifi/rd-loop.md",
    "docs/projects/four-relay-xbee-wifi/mains-readiness-gate.md",
    "docs/projects/four-relay-xbee-wifi/power-and-safety.md",
    "docs/projects/four-relay-xbee-wifi/pin-plan.md",
    "docs/projects/four-relay-xbee-wifi/firmware-task-model.md",
    "docs/projects/four-relay-xbee-wifi/web-interface.md",
    "docs/projects/four-relay-xbee-wifi/ui/index.html",
    "docs/projects/four-relay-xbee-wifi/ui/styles.css",
    "docs/projects/four-relay-xbee-wifi/ui/app.js",
    "docs/projects/four-relay-xbee-wifi/ui/manifest.json",
    "docs/projects/four-relay-xbee-wifi/ui/assets/.gitkeep",
    "docs/prompt/prompt-triage.md",
    "docs/prompt/preengineered-prompts.md",
    "docs/prompt/autoencoded-model-selection.md",
    "knowledge-base/source-index.md",
    "knowledge-base/model-profiles.md",
    "knowledge-base/prompt-registry.md",
    "knowledge-base/source-ledger/2026-05-18-four-relay-xbee-wifi-design.md",
    "knowledge-base/source-ledger/2026-05-18-esp32project-photo-analysis.md",
    "knowledge-base/source-ledger/2026-05-18-diy-bench-hardware-blockers.md",
    "knowledge-base/source-ledger/2026-05-18-spi-microsd-assets-logs.md",
    "knowledge-base/source-ledger/2026-05-18-xbee-read-only-bench-proof.md",
    "knowledge-base/source-ledger/2026-05-19-four-relay-hardware-circuit-improvement.md",
    "knowledge-base/source-ledger/2026-05-19-expert-agent-panels.md",
    "knowledge-base/source-ledger/2026-05-19-github-pages-expert-panels.md",
    "knowledge-base/toolchain/four-relay-xbee-wifi-toolchain.md",
    "research/known-gaps.md",
    "research/triage-status.md",
    "research/skills/available-skills.md",
    "research/bench-records/TEMPLATE.md",
    "hardware-profiles/device-matrix.md",
    "hardware-profiles/esp32/esp-wroom-32-dev-board/README.md",
    "hardware-profiles/esp32/devkitc/README.md",
    "hardware-profiles/storage/spi-microsd-reader/README.md",
    "hardware-profiles/xbee/xbp9b-dput-001/README.md",
    "hardware-profiles/xbee/waveshare-xbee-usb-adapter/README.md",
    "hardware-profiles/relays/single-channel/README.md",
    "hardware-profiles/relays/four-channel/README.md",
    "hardware-profiles/relays/eight-channel/README.md",
    "hardware-profiles/relays/sixteen-channel/README.md",
    "hardware-profiles/heltec/wifi-lora32-v2/README.md",
    "hardware-profiles/displays/open-smart-r61509v/README.md",
    "hardware-profiles/interface-expansion/cd74hc4067/README.md",
    "hardware-profiles/interface-expansion/tca9555-mcp23017/README.md",
    "hardware-profiles/interface-expansion/tpic6b595/README.md",
    "comm-protocols/wireless/xbee-api-four-relay.md",
    "firmware/interfaces/README.md",
    "firmware/boards/README.md",
    "firmware/comms/README.md",
    "firmware/projects/four-relay-xbee-wifi/README.md",
    "firmware/projects/four-relay-xbee-wifi/CMakeLists.txt",
    "firmware/projects/four-relay-xbee-wifi/main/CMakeLists.txt",
    "firmware/projects/four-relay-xbee-wifi/main/main.c",
    "firmware/projects/four-relay-xbee-wifi/components/safe_core/CMakeLists.txt",
    "firmware/projects/four-relay-xbee-wifi/components/safe_core/include/four_relay_core.h",
    "firmware/projects/four-relay-xbee-wifi/components/safe_core/src/api_contract.c",
    "firmware/projects/four-relay-xbee-wifi/components/safe_core/src/api_model.c",
    "firmware/projects/four-relay-xbee-wifi/components/safe_core/src/config_store.c",
    "firmware/projects/four-relay-xbee-wifi/components/safe_core/src/relay_state.c",
    "firmware/projects/four-relay-xbee-wifi/components/safe_core/src/safety_supervisor.c",
    "firmware/projects/four-relay-xbee-wifi/components/safe_core/src/storage_status.c",
    "firmware/projects/four-relay-xbee-wifi/components/safe_core/src/xbee_frame.c",
    "tests/four_relay_safe_core/run_host_tests.py",
    "tests/four_relay_safe_core/test_support.h",
    "tests/four_relay_safe_core/test_relay_safety.c",
    "tests/four_relay_safe_core/test_http_api_contracts.c",
    "tests/four_relay_safe_core/test_storage_contracts.c",
    "tests/four_relay_safe_core/test_xbee_frame_codec.c",
    "tests/scaffold_audits/test_source_image_scan.py",
    "site/github-pages/index.html",
    "site/github-pages/blueprints.html",
    "site/github-pages/quality.html",
    "site/github-pages/styles.css",
    "site/github-pages/app.js",
    "site/github-pages/site-data.json",
    "site/github-pages/404.html",
    "site/github-pages/.nojekyll",
    "site/github-pages/assets/blueprints/system-overview.webp",
    "site/github-pages/assets/blueprints/safety-proof-ladder.webp",
    "site/github-pages/assets/workbench/hero-workbench.webp",
    "site/github-pages/assets/workbench/rd-loop-backplate.webp",
    "site/github-pages/assets/workbench/admin-hmi-backplate.webp",
    "scripts/build_github_pages.py",
    "scripts/audit_public_manifest.py",
    "scripts/smoke_github_pages.py",
    "scripts/xbee_read_only_probe.py",
    "scripts/scaffold_audit_data.py",
    "scripts/scaffold_audit_paths.py",
    "scripts/scaffold_audit_sources.py",
    "scripts/scaffold_audit_docs.py",
    "scripts/scaffold_audit_firmware.py",
    "scripts/scaffold_audit_pages.py",
    ".github/workflows/README.md",
    ".github/workflows/pages.yml",
]

PROHIBITED_FRAMEWORK_FILES = [
    "CMakeLists.txt",
    "sdkconfig",
    "platformio.ini",
    "idf_component.yml",
    "arduino-cli.yaml",
]

ALLOWED_PROJECT_FRAMEWORK_FILES = {
    "firmware/projects/four-relay-xbee-wifi/CMakeLists.txt",
    "firmware/projects/four-relay-xbee-wifi/main/CMakeLists.txt",
    "firmware/projects/four-relay-xbee-wifi/components/safe_core/CMakeLists.txt",
}

FIRMWARE_SOURCE_SCAN_ROOT = ROOT / "firmware" / "projects" / "four-relay-xbee-wifi"
FORBIDDEN_FIRMWARE_MARKERS = [
    "gpio_set_level",
    "gpio_config",
    "uart_write_bytes",
    "i2c_master_write",
    "esp_wifi_start",
    "httpd_start",
    "esp_vfs_fat",
    "esp_partition_erase",
    "idf.py flash",
    "idf.py monitor",
]

PROJECT_FACT_PATHS = [
    "docs/projects/four-relay-xbee-wifi/README.md",
    "docs/projects/four-relay-xbee-wifi/build-guide.md",
    "docs/projects/four-relay-xbee-wifi/architecture.md",
    "docs/projects/four-relay-xbee-wifi/prototype-blueprint.md",
    "docs/projects/four-relay-xbee-wifi/bench-bring-up-runbook.md",
    "docs/projects/four-relay-xbee-wifi/xbee-read-only-bench-proof.md",
    "docs/projects/four-relay-xbee-wifi/hardware-circuit-improvement-research.md",
    "docs/projects/four-relay-xbee-wifi/rd-loop.md",
    "docs/projects/four-relay-xbee-wifi/mains-readiness-gate.md",
    "docs/projects/four-relay-xbee-wifi/power-and-safety.md",
    "docs/projects/four-relay-xbee-wifi/pin-plan.md",
    "docs/projects/four-relay-xbee-wifi/firmware-task-model.md",
    "docs/projects/four-relay-xbee-wifi/web-interface.md",
    "docs/github-pages-public-site.md",
    "knowledge-base/source-ledger/2026-05-18-four-relay-xbee-wifi-design.md",
    "knowledge-base/source-ledger/2026-05-18-esp32project-photo-analysis.md",
    "knowledge-base/source-ledger/2026-05-18-diy-bench-hardware-blockers.md",
    "knowledge-base/source-ledger/2026-05-18-spi-microsd-assets-logs.md",
    "knowledge-base/source-ledger/2026-05-18-xbee-read-only-bench-proof.md",
    "knowledge-base/source-ledger/2026-05-19-four-relay-hardware-circuit-improvement.md",
    "knowledge-base/toolchain/four-relay-xbee-wifi-toolchain.md",
    "firmware/projects/four-relay-xbee-wifi/README.md",
    "hardware-profiles/device-matrix.md",
    "hardware-profiles/esp32/esp-wroom-32-dev-board/README.md",
    "hardware-profiles/esp32/devkitc/README.md",
    "hardware-profiles/storage/spi-microsd-reader/README.md",
    "hardware-profiles/relays/four-channel/README.md",
    "hardware-profiles/xbee/xbp9b-dput-001/README.md",
    "hardware-profiles/xbee/waveshare-xbee-usb-adapter/README.md",
    "comm-protocols/wireless/xbee-api-four-relay.md",
]

PHOTO_LEDGER_PATH = "knowledge-base/source-ledger/2026-05-18-esp32project-photo-analysis.md"

PHOTO_FILENAMES = [
    "IMG_5678.jpeg",
    "IMG_5679.jpeg",
    "IMG_5680.jpeg",
    "IMG_5681.jpeg",
    "IMG_5682.jpeg",
    "IMG_5683.jpeg",
    "IMG_5684.jpeg",
    "IMG_5685.jpeg",
    "IMG_5686.jpeg",
    "IMG_5687.jpeg",
]

SOURCE_ID_PATTERN = re.compile(r"\bSRC-[A-Z0-9-]+\b")

REQUIRED_SOURCE_IDS = [
    "SRC-OPENAI-LATEST-MODEL",
    "SRC-GITHUB-PAGES-WHAT-IS",
    "SRC-GITHUB-PAGES-PUBLISHING-SOURCE",
    "SRC-GITHUB-PAGES-CUSTOM-WORKFLOWS",
    "SRC-GITHUB-PAGES-LIMITS",
    "SRC-ESP-IDF-LATEST",
    "SRC-ESP-IDF-STABLE-ESP32",
    "SRC-ESP-IDF-GET-STARTED",
    "SRC-ESP-IDF-HTTP-SERVER",
    "SRC-ESP-IDF-WIFI",
    "SRC-ESP-IDF-GPIO",
    "SRC-ESP-IDF-UART",
    "SRC-ESP-IDF-NVS",
    "SRC-ESP-IDF-FATFS",
    "SRC-ESP-IDF-SDSPI",
    "SRC-ESP-IDF-SDMMC",
    "SRC-ESP-IDF-SD-PULLUP",
    "SRC-ESP-IDF-RESTFUL-SERVER-EXAMPLE",
    "SRC-ESP-IDF-SDSPI-EXAMPLE",
    "SRC-ESP-IDF-FATAL-BROWNOUT",
    "SRC-SD-ASSOCIATION-FORMATTER",
    "SRC-SD-ASSOCIATION-CAPACITY",
    "SRC-ESP32-WROOM-32-DATASHEET",
    "SRC-ESP32-HARDWARE-DESIGN-GUIDELINES",
    "SRC-ESP32-DEVKITC",
    "SRC-DIGI-XBP9B-DPUT-001",
    "SRC-DIGI-XBEE-PRO-900HP",
    "SRC-DIGI-XBEE-900HP-USER-GUIDE",
    "SRC-DIGI-XBEE-900HP-AP",
    "SRC-DIGI-XBEE-900HP-AO",
    "SRC-DIGI-XBEE-900HP-DELIVERY",
    "SRC-DIGI-XBEE-900HP-NP",
    "SRC-DIGI-XCTU",
    "SRC-LOCAL-TOOLCHAIN-PROBE-2026-05-18",
    "SRC-LOCAL-XBEE-READONLY-PROBE-2026-05-18",
    "SRC-LOCAL-FOUR-RELAY-SAFE-CORE-CONTRACT-2026-05-19",
    "SRC-LOCAL-GITHUB-PAGES-EXPERT-PANELS-2026-05-19",
    "SRC-LOCAL-ESP32PROJECT-PHOTOS-2026-05-18",
    "SRC-ESP32-IO-SHIELD-CANDIDATE",
    "SRC-TI-LM66100",
    "SRC-LITTELFUSE-16R-PPTC",
    "SRC-LITTELFUSE-SLVU2-8-TVS",
    "SRC-HELTEC-WIFI-LORA-32-V2",
    "SRC-WAVESHARE-XBEE-USB-ADAPTER",
    "SRC-SONGLE-SRD-05VDC-SL-C",
    "SRC-NIOSH-ELECTRICAL-SAFETY",
    "SRC-OSHA-DEENERGIZED-WORK",
    "SRC-OSHA-GFCI",
    "SRC-OSHA-AEGCP",
    "SRC-OSHA-GROUNDING-OVERCURRENT",
    "SRC-OSHA-1910-305",
    "SRC-NEMA-ENCLOSURES",
    "SRC-NEMA-250-ENCLOSURES",
    "SRC-TI-CD74HC4067",
    "SRC-TI-TCA9555",
    "SRC-ESPRESSIF-MCP23017-COMPONENT",
    "SRC-TI-TPIC6B595",
    "SRC-TI-ULN2003A",
    "SRC-FLUKE-87V",
    "SRC-KEYSIGHT-E36200",
    "SRC-SALEAE-LOGIC-8",
]

ALLOWED_IMAGE_BINARY_PATHS = {
    "site/github-pages/assets/blueprints/system-overview.webp",
    "site/github-pages/assets/blueprints/safety-proof-ladder.webp",
    "site/github-pages/assets/workbench/hero-workbench.webp",
    "site/github-pages/assets/workbench/rd-loop-backplate.webp",
    "site/github-pages/assets/workbench/admin-hmi-backplate.webp",
}

IMAGE_SUFFIXES = {".gif", ".jpeg", ".jpg", ".png", ".webp"}
